version: '3.8'

services:
  # 1. Ma'lumotlar bazasi (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
      POSTGRES_DB: ${DB_NAME:-nest_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Redis kesh uchun
  redis:
    image: redis:7-alpine
    container_name: nest_redis
    restart: always
    ports:
      - '6379:6379'

  # 3. NestJS Backend
  api:
    build: .
    container_name: nest_api
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: 'postgresql://${DB_USERNAME:-postgres}:${DB_PASSWORD:-secret}@db:5432/${DB_NAME:-nest_db}?schema=public'
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      # Boshqa muhit o'zgaruvchilari
    volumes:
      - .env:/app/.env

volumes:
  postgres_data:
