-- AlterTable
ALTER TABLE "Comment" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Course" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "InstructorProfile" ALTER COLUMN "rating" SET DATA TYPE DOUBLE PRECISION;
